# Generated by Django 4.1.3 on 2022-11-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartype', models.CharField(choices=[('C', 'CAR'), ('T', 'TRUCK'), ('M', 'MOTORCYCLE')], default='C', max_length=3)),
                ('number', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
            ],
        ),
    ]
