# Generated by Django 4.1.3 on 2022-11-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/car.png', null=True, upload_to=''),
        ),
    ]
